version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build
  run_codacy:
    machine: true
    steps:
      - checkout
      - run: curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
      - run: cd codacy-analysis-cli-* && sudo make install
      - run: codacy-analysis-cli analyse --verbose --max-allowed-issues 500
      - run: find .
workflows:
  version: 2
  build_and_check:
    jobs:
      - build
      - run_codacy