version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build
  run_codacy:
    docker:
      - image: openjdk:12-jdk
    steps:
      - run: java --version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - run_codacy