version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build
  run_codacy:
    docker:
      - image: docker:latest
      - image: buildpack-deps:trusty
    steps:
      - run: curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
      - run: cd codacy-analysis-cli-* && sudo make install --retry-connrefused http://localhost:8080
      - run: codacy-analysis-cli
workflows:
  version: 2
  build_and_check:
    jobs:
      - build
      - run_codacy