version: 2.1
orbs:
  messagebird-sms:
    commands:
      sendsms:
        description: Send SMS notifications using Messagebird
        parameters:
          originator:
            description: >
              The sender of the message. This can be a telephone number (including country code) or an alphanumeric string. 
              In case of an alphanumeric string, the maximum length is 11 characters. 
            type: string
            default: ${MESSAGEBIRD_ORIGINATOR}
          recipients:
            description: >
              This parameter determines the destination phone number for your SMS message. \
              Format this number with a '+' and a country code, e.g., +16175551212 (E.164 format).
              Maximum 50 recipients
            type: string
            default: ${MESSAGEBIRD_RECIPIENTS}
          body:
            description: The body of the SMS message.
            type: string
            default: "Do not forget to customise the message body!"
          accesskey:
            description: Access key.
            type: string
            default: ${MESSAGEBIRD_ACCESSKEY}
        steps:
          - run: echo "test"
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build
      - messagebird-sms/sendsms:
          body: "some random text"
  run_codacy:
    machine: true
    steps:
      - run: curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
      - run: cd codacy-analysis-cli-* && sudo make install
      - run: find .
      - run: cd ..
      - run: checkout
      - run: codacy-analysis-cli analyse --tool sonar-csharp
workflows:
  build_and_check:
    jobs:
      - build