version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build
  run_codacy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - setup_remote_docker
      - run: find .
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
      - run: cd codacy-analysis-cli-* && sudo make install --retry-connrefused http://localhost:8080
      - run: codacy-analysis-cli
workflows:
  version: 2
  build_and_check:
    jobs:
      - build
      - run_codacy