version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build
  run_codacy:
    machine: true
    steps:
      - run: curl -L https://github.com/codacy/codacy-analysis-cli/archive/master.tar.gz | tar xvz
      - run: cd codacy-analysis-cli-* && sudo make install
      - run: codacy-analysis-cli
      - run: find .
  run_codacy_docker:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - run: |
          name: Run codacy
          command: |
            docker run \
            --rm=true \
            --env CODACY_CODE="$CODACY_CODE" \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume "$CODACY_CODE":"$CODACY_CODE" \
            --volume /tmp:/tmp \
            codacy/codacy-analysis-cli \
              analyse --tool <TOOL-SHORT-NAME>
workflows:
  version: 2
  build_and_check:
    jobs:
      - build
      - run_codacy
      - run_codacy_docker